name: CI Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run vue tests
        run: echo "\n\n!!!!! Really need to add vue test here !!!!!\n\n"
      - id: tagger
        uses: coopstools-homebrew/deep-sea-currents@v0.0.2
      - name: Print version again
        run: echo "version - ${{ steps.tagger.outputs.tag }}"
